
spring:
  jackson:
    time-zone: GMT+8
  # 关闭模板引擎的缓存
  thymeleaf:
    cache: false
  #我们的配置文件的真实位置
  messages:
    basename: i18n.login
  mvc:
    date-format: yyyy-MM-dd
  datasource:
    username: root
    password: 123456
    url: jdbc:mysql://localhost:3306/database1?serverTimezone=UTC&useUnicode=true&characterEncoding=utf-8
    driver-class-name: com.mysql.cj.jdbc.Driver


# 整合mybatis
mybatis:
  type-aliases-package: com.example.demo.pojo
  mapper-locations: classpath:mybatis/mapper/*.xml
